# Header
menu:
  Home: /
  Archives: /archives
  Album: /instagram
  AboutMe: /aboutme
  
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/"
  weibo: "http://weibo.com/thankforyou"
  #rss: "http://feed.feedsky.com/vale"
  #facebook: "https://www.facebook.com/changwei.tu.3"
  #google: "#"
  twitter: "https://twitter.com/ValeTu_1988"
  linkedin: "http://cn.linkedin.com/pub/vale-tu/71/527/3a1/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像
avatar: "https://avatars0.githubusercontent.com/u/2604045?v=2&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
	
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: true
#开启——
friends:
  威威的博客: http://wedcel.com
  

#是否开启“关于我”。
#不开启——
#aboutme: true
#开启——
#aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…